### ISSUE TITLE
打包上传App Store时报动态库的错误

### ISSUE THREAD

**Issue by zhaoychehe** [Lojii/Knot#11]
ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.NIOSSL' under the iOS application 'FTInspectioned.app'."
ERROR ITMS-90205: "Invalid Bundle. The bundle at 'FTInspectioned.app/Frameworks/NIO.framework' contains disallowed nested bundles."
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'FTInspectioned.app/Frameworks/NIO.framework' contains disallowed file 'Frameworks'."
参考以下解决方式无效
[https://www.jianshu.com/p/de4d87f9d4e5](https://www.jianshu.com/p/de4d87f9d4e5) 
[https://blog.csdn.net/yaojinhai06/article/details/85410916](https://blog.csdn.net/yaojinhai06/article/details/85410916)

**Comment by Lojii** [comment]
不清楚你具体改了哪些地方，仅做参考
ERROR ITMS-90685:  使用org.NIOSSL的不止一个，你看一下那里面几个Extension是不是用重复了
ERROR ITMS-90205-90206: 这个感觉是NIO.framework被重复引入，或者循环依赖，你检查下都有哪些target包含这个framework，现在SwiftNIO已经很成熟了，你可以试着用CocoaPod的方式引入，应该可以避免这种问题

如果上架成功了，来push点代码鸭

**Comment by XiaoJiuDYS** [comment]
前来围观🤪

**Comment by zhaoychehe** [comment]
问题解决了，每个包含子动态库的动态库都要采用上述方式处理下。另外可以使用pod的方式，但有几个方法是私有的，需要单独处理下。已经可以打包上传，期待过审。

**Comment by Lojii** [comment]
> 问题解决了，每个包含子动态库的动态库都要采用上述方式处理下。另外可以使用pod的方式，但有几个方法是私有的，需要单独处理下。已经可以打包上传，期待过审。

审核结果如何？过了么

**Comment by zhaoychehe** [comment]
Your app uses public APIs in an unapproved manner, which does not comply with guideline 2.5.1 of the App Store Review Guidelines.
Specifically, your app use NEVPNManager APIs for non-VPN app.
Since there is no accurate way of predicting how an API may be modified and what effects those modifications may have, Apple does not permit unapproved uses of public APIs in App Store apps.
审核没过。
参考此解决方案 https://www.v2ex.com/amp/t/524107
还有一种解决方案就是上线隐藏此功能，运行时动态调用NEVPNManager相关api。

**Comment by Lojii** [comment]
这条审核规则是19年6月份新增的

**Comment by zhaoychehe** [comment]
打算先走企业证书，但是企业证书重签名后启动闪退，和动态库或者扩展工程有关系吗

**Comment by zhaoychehe** [comment]
> 打算先走企业证书，但是企业证书重签名后启动闪退，和动态库或者扩展工程有关系吗

问题解决了，共享下。是因为企业重签名导致appgroup这块异常，没有做异常处理

**Comment by fakers777** [comment]
APP可以给自己装吗，能否给个APP，自己用一下呢。两位大佬
