### ISSUE TITLE
VPN error???

### ISSUE THREAD

**Issue by MuZiLee** [Lojii/Knot#18]
Warning(7): is not general line !
Warning(8): is not general line !
Warning(9): is not general line !
Warning(10): is not general line !
***************SFVPNManager startStopToggled
starting!!!
VPN Status:Connecting
getAll error:no such table: session (code: 1)
VPN Status:Disconnected
getAll error:no such table: session (code: 1)

我点击run之后就会出现以上错误。
请问出现以上的问题应该怎么解决？

**Comment by League2EB** [comment]
@Lojii @MuZiLee 同样问题，请大神求解，非常谢谢！

**Comment by Lojii** [comment]
需要设置App Group，数据库是通过App Group在主程序与NetworkExtension之间实现共享的，没有设置App Group会找不到对应的数据库和table

**Comment by League2EB** [comment]
@Lojii 我有设定，但不确定哪里设置错误，请前辈教导指正

![](https://i.loli.net/2021/11/04/uwMHvRGzT6lCdDB.png)

![](https://i.loli.net/2021/11/04/8x1pE4eF3Rzftig.png)

![](https://i.loli.net/2021/11/04/2sqB3LbtcerNVi7.png)

![](https://i.loli.net/2021/11/04/Zy2cB9dP3RqLwsX.png)

![](https://i.loli.net/2021/11/04/JoDPAZkdzOYw2VK.png)

**Comment by Lojii** [comment]
TunnelServices/MitmService.swift  里16行，也需要修改下

**Comment by League2EB** [comment]
> TunnelServices/MitmService.swift 里16行，也需要修改下

修改后问题仍然存在

![](https://i.imgur.com/M65ayY4.png)

**Comment by 0xsunsama** [comment]
> > TunnelServices/MitmService.swift 里16行，也需要修改下
> 
> 修改后问题仍然存在
> 
> ![](https://camo.githubusercontent.com/166b402ea19a0dfeaecf0e91102bf032dad491d97a2e11746ef4b58a3e6eb619/68747470733a2f2f692e696d6775722e636f6d2f4d3635617959342e706e67)



> > TunnelServices/MitmService.swift 里16行，也需要修改下
> 
> 修改后问题仍然存在
> 
> ![](https://camo.githubusercontent.com/166b402ea19a0dfeaecf0e91102bf032dad491d97a2e11746ef4b58a3e6eb619/68747470733a2f2f692e696d6775722e636f6d2f4d3635617959342e706e67)

应该是nio.db 中的session表没有创建，我也遇到这个问题了。好像不是AppGroup的问题

**Comment by flywithbug** [comment]
group设置 修改过也是一样的问题，

**Comment by flywithbug** [comment]
@Lojii  大佬有空解答一下疑惑

**Comment by Tuluobo** [comment]
需要检查 `providerBundleIdentifier` 属性是否是自己修改的，把这个配置一下就 OK 吧

**Comment by sdualasijia** [comment]
> @Lojii 大佬有空解答一下疑惑

这个问题你解决了吗

**Comment by orangeboyChen** [comment]
> > @Lojii 大佬有空解答一下疑惑
> 
> 这个问题你解决了吗

看了下代码，因为数据库没有建表引起的
<img width="1313" alt="Screen Shot 2022-10-25 at 15 43 31" src="https://user-images.githubusercontent.com/27876299/197713601-27b91888-352d-436b-998d-c03330a037e0.png">
在AppDelegate加入28行暂时解决，暂时未发现副作用，希望作者大大可以解决下～

**Comment by ByteSecurity** [comment]
> getAll error:no such table: session (code: 1)

@orangeboyChen 虽然不报错了, 还是不行. 好奇怪 (ios 14)

`
***[info]***-ASProtocol+Schame.swift[41]:createTable() --> Create  Table Task success

***************SFVPNManager startStopToggled

starting!!!

VPN Status:Connecting

VPN Status:Disconnected

`
