### ISSUE TITLE
NIO报错

### ISSUE THREAD

**Issue by bing89757** [Lojii/Knot#24]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/33313876/169647581-8b851816-9884-43de-9f4d-7a43771b8f31.png">
大佬这个怎么解决

**Comment by bing89757** [comment]
需要升级NIO库吗

**Comment by Tuluobo** [comment]
> 需要升级NIO库吗

从这里 https://github.com/apple/swift-nio.git 找到报错文件，替换掉对应的报错的部分，就 ok 了
