### ISSUE TITLE
问题较多

### ISSUE THREAD

**Issue by Dcell** [Lojii/Knot#3]
1.已经配置好证书和App Group
问题较多。
![屏幕快照 2020-02-28 上午9 23 42](https://user-images.githubusercontent.com/4684864/75501879-2bd97380-5a0c-11ea-8798-52bab7ec3d80.png)
Calling syncShutdownGracefully() on any EventLoop can lead to deadlocks.
几乎必现。
2.侥幸没有进断言，正常打开了
VPN Target进程 必闪退，还没时间查看问题。

希望楼主改进下。

**Comment by Lojii** [comment]
iOS13 ?

**Comment by Dcell** [comment]
死锁的问题，应该逻辑存在问题，VPN 进程挂了的问题，我还没时间看，后头我把问题贴上来。

**Comment by Lojii** [comment]
兄嘚，贴下你的环境先，我也去看看

**Comment by Dcell** [comment]
版本 12.1 ，iPhone6 
工程用Xcode11.1

**Comment by Dcell** [comment]
https://github.com/Lojii/Knot/blob/eccde7e229e36ca36d32635322f361cc7d1f286f/TunnelServices/HttpService/SSLServer.swift#L230
死锁的地方，在Loop里面，调用同步函数。

**Comment by Lojii** [comment]
SSLServer是主进程里用来检测证书是否被安装与信任的，这句是关闭启动的SSL服务线程，我这边试了没问题，不知道是啥情况，如果频繁进断点，把这句注释掉也是没什么大问题的，这只是会造成主进程里的句柄泄漏，不过在App的生命周期里调用次数不会很多，所以就算有句柄泄漏，也不会造成什么影响

**Comment by ghost** [comment]
这边也能复现,iOS 13.4. Xcode 11.4 beta 3
